# Generated by Django 5.0.7 on 2024-07-12 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aluraflix', '0005_alter_video_categoria'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='categoria',
            field=models.ManyToManyField(default=1, to='aluraflix.categoria'),
        ),
    ]
