# Generated by Django 5.0.7 on 2024-07-12 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aluraflix', '0009_alter_video_categoria'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='categoria',
            field=models.ManyToManyField(blank=True, to='aluraflix.categoria'),
        ),
    ]
